const MOBILE_DATABASE = {
  "Apple iPhone": [
    "Apple iPhone 17",
    "Apple iPhone 17 Air (Only Back)",
    "Apple iPhone 17 Pro",
    "Apple iPhone 17 Pro Max",
    "Apple iPhone 16",
    "Apple iPhone 16e",
    "Apple iPhone 16 Plus",
    "Apple iPhone 16 Pro",
    "Apple iPhone 16 Pro Max",
    "Apple iPhone 15",
    "Apple iPhone 15 Plus",
    "Apple iPhone 15 Pro",
    "Apple iPhone 15 Pro Max",
    "Apple iPhone 14",
    "Apple iPhone 14 Plus",
    "Apple iPhone 14 Pro",
    "Apple iPhone 14 Pro Max",
    "Apple iPhone 13",
    "Apple iPhone 13 Mini",
    "Apple iPhone 13 Pro",
    "Apple iPhone 13 Pro Max",
    "Apple iPhone 12",
    "Apple iPhone 12 Mini",
    "Apple iPhone 12 Pro",
    "Apple iPhone 12 Pro Max",
    "Apple iPhone 11",
    "Apple iPhone 11 Pro",
    "Apple iPhone 11 Pro Max",
    "Apple iPhone XS",
    "Apple iPhone XS Max",
    "Apple iPhone X",
    "Apple iPhone XR",
    "Apple iPhone SE (2022)",
    "Apple iPhone SE (2020)",
    "Apple iPhone 8",
    "Apple iPhone 8 Plus",
    "Apple iPhone 7",
    "Apple iPhone 7 Plus",
    "Apple iPhone 6",
    "Apple iPhone 6 Plus",
    "Apple iPhone 6S",
    "Apple iPhone 6S Plus",
    "Apple iPhone SE",
    "Apple iPhone 5S",
    "Apple iPhone 5C",
    "Apple iPhone 5",
    "Apple iPhone 4",
    "Apple iPhone 4S"
  ],
  "OnePlus": [
    "OnePlus X",
    "Oneplus One",
    "Oneplus Two",
    "OnePlus 3",
    "OnePlus 3T",
    "OnePlus 5",
    "OnePlus 5T",
    "OnePlus 6",
    "OnePlus 6T",
    "OnePlus 7",
    "OnePlus 7 Pro",
    "OnePlus 7T",
    "OnePlus 7T Pro",
    "OnePlus 8",
    "OnePlus 8T",
    "OnePlus 8 Pro",
    "OnePlus 9",
    "OnePlus 9 Pro",
    "OnePlus 9R",
    "OnePlus 9RT (5G)",
    "OnePlus 10T (5G)",
    "OnePlus 10R (5G)",
    "OnePlus 10 Pro (5G)",
    "OnePlus 11 (5G)",
    "OnePlus 11R (5G)",
    "OnePlus 12 (5G)",
    "OnePlus 12R (5G)",
    "OnePlus 13 (5G)",
    "OnePlus 13R (5G)",
    "OnePlus 13S (5G)",
    "OnePlus 13T (5G)",
    "OnePlus 15 (5G)",
    "OnePlus 15R (5G)",
    "OnePlus Nord",
    "Oneplus Nord 2 (5G)",
    "Oneplus Nord 2T (5G)",
    "OnePlus Nord 3 (5G)",
    "OnePlus Nord 4 (5G)",
    "OnePlus Nord 5 (5G)",
    "OnePlus Nord 6 (5G)",
    "OnePlus Nord CE (5G)",
    "OnePlus Nord CE 2 (5G)",
    "OnePlus Nord CE 2 Lite (5G)",
    "OnePlus Nord CE 3 (5G)",
    "OnePlus Nord CE 3 Lite (5G)",
    "OnePlus Nord CE 4 (5G)",
    "OnePlus Nord CE 4 Lite (5G)",
    "OnePlus Nord CE 5 (5G)",
    "OnePlus Nord CE 6 (5G)",
    "OnePlus Nord CE 6 Lite (5G) (Only Back)",
    "OnePlus Nord N10 (5G)",
    "OnePlus Nord N20 (5G) (Only Back)",
    "OnePlus Nord N20 SE (Only Back)",
    "OnePlus Nord N100 (Only Back)",
    "OnePlus Nord N200 (5G)",
    "OnePlus Open (5G)"
  ],
  "Samsung": [
    "Samsung Galaxy A01",
    "Samsung Galaxy A02",
    "Samsung Galaxy A02s",
    "Samsung Galaxy A03",
    "Samsung Galaxy A03s",
    "Samsung Galaxy A03 Core",
    "Samsung Galaxy A04",
    "Samsung Galaxy A04e",
    "Samsung Galaxy A04s",
    "Samsung Galaxy A05",
    "Samsung Galaxy A05s",
    "Samsung Galaxy A06",
    "Samsung Galaxy A06 (5G)",
    "Samsung Galaxy A07",
    "Samsung Galaxy A07 (5G)",
    "Samsung Galaxy A2 Core",
    "Samsung Galaxy A3 2015",
    "Samsung Galaxy A3 2016",
    "Samsung Galaxy A3 2017",
    "Samsung Galaxy A5 2015",
    "Samsung Galaxy A5 2016",
    "Samsung Galaxy A5 2017",
    "Samsung Galaxy A6",
    "Samsung Galaxy A6 Plus 2018",
    "Samsung Galaxy A7 2015",
    "Samsung Galaxy A7 2016",
    "Samsung Galaxy A7 2017",
    "Samsung Galaxy A7 2018",
    "Samsung Galaxy A8S",
    "Samsung Galaxy A8 Plus",
    "Samsung Galaxy A8 Star",
    "Samsung Galaxy A8 2016",
    "Samsung Galaxy A8 2017",
    "Samsung Galaxy A8 2018",
    "Samsung Galaxy A9",
    "Samsung Galaxy A9 2016",
    "Samsung Galaxy A9 2018",
    "Samsung Galaxy A9 Pro",
    "Samsung Galaxy A10",
    "Samsung Galaxy A10S",
    "Samsung Galaxy A11 2020",
    "Samsung Galaxy A12",
    "Samsung Galaxy A13 (4G)",
    "Samsung Galaxy A13 (5G) (Only Back)",
    "Samsung Galaxy A14 (5G)",
    "Samsung Galaxy A15 (5G)",
    "Samsung Galaxy A16 (5G)",
    "Samsung Galaxy A17 (5G)",
    "Samsung Galaxy A20",
    "Samsung Galaxy A20E (No Sides)",
    "Samsung Galaxy A20S",
    "Samsung Galaxy A21 (No Sides)",
    "Samsung Galaxy A21S",
    "Samsung Galaxy A22",
    "Samsung Galaxy A22 (5G)",
    "Samsung Galaxy A23 (4G)",
    "Samsung Galaxy A23 (5G)",
    "Samsung Galaxy A24 (4G)",
    "Samsung Galaxy A25 (5G)",
    "Samsung Galaxy A26 (5G)",
    "Samsung Galaxy A30",
    "Samsung Galaxy A30s",
    "Samsung Galaxy A31",
    "Samsung Galaxy A32 (4G)",
    "Samsung Galaxy A32 (5G)",
    "Samsung Galaxy A33 (5G)",
    "Samsung Galaxy A34 (5G)",
    "Samsung Galaxy A35 (5G)",
    "Samsung Galaxy A36 (5G)",
    "Samsung Galaxy A37 (5G)",
    "Samsung Galaxy A40",
    "Samsung Galaxy A41",
    "Samsung Galaxy A42 (5G) (Only Back)",
    "Samsung Galaxy A50",
    "Samsung Galaxy A50S",
    "Samsung Galaxy A51",
    "Samsung Galaxy A52",
    "Samsung Galaxy A52s (5G)",
    "Samsung Galaxy A53 (5G)",
    "Samsung Galaxy A54 (5G)",
    "Samsung Galaxy A55 (5G)",
    "Samsung Galaxy A56 (5G)",
    "Samsung Galaxy A57 (5G)",
    "Samsung Galaxy A60",
    "Samsung Galaxy A70",
    "Samsung Galaxy A70S",
    "Samsung Galaxy A71",
    "Samsung Galaxy A72",
    "Samsung Galaxy A73 (5G)",
    "Samsung Galaxy A80",
    "Samsung Galaxy A81",
    "Samsung Galaxy Alpha",
    "Samsung Galaxy C5",
    "Samsung Galaxy C5 Pro",
    "Samsung Galaxy C7",
    "Samsung Galaxy C7 2016",
    "Samsung Galaxy C7 2017",
    "Samsung Galaxy C7 Pro",
    "Samsung Galaxy C9",
    "Samsung Galaxy C9 Pro",
    "Samsung Galaxy Core 2",
    "Samsung Galaxy E5",
    "Samsung Galaxy E7",
    "Samsung Galaxy F04",
    "Samsung Galaxy F05",
    "Samsung Galaxy F06 (5G)",
    "Samsung Galaxy F12",
    "Samsung Galaxy F13",
    "Samsung Galaxy F14 (5G)",
    "Samsung Galaxy F15 (5G)",
    "Samsung Galaxy F16 (5G)",
    "Samsung Galaxy F17 (5G)",
    "Samsung Galaxy F22",
    "Samsung Galaxy F23 (5G)",
    "Samsung Galaxy F34 (5G)",
    "Samsung Galaxy F41",
    "Samsung Galaxy F42 (5G)",
    "Samsung Galaxy F54 (5G)",
    "Samsung Galaxy F55 (5G)",
    "Samsung Galaxy F56 (5G)",
    "Samsung Galaxy F62",
    "Samsung Galaxy Grand 2",
    "Samsung Galaxy Grand 3",
    "Samsung Galaxy Grand Max",
    "Samsung Galaxy Grand Neo",
    "Samsung Galaxy Grand Prime",
    "Samsung Galaxy Grand Quattro",
    "Samsung Galaxy J1 2016",
    "Samsung Galaxy J2 2015",
    "Samsung Galaxy J2 2016",
    "Samsung Galaxy J2 2018 (No Sides)",
    "Samsung Galaxy J2 Core",
    "Samsung Galaxy J2 Core 2018",
    "Samsung Galaxy J2 Pro",
    "Samsung Galaxy J2 Pro 2018",
    "Samsung Galaxy J3 2015",
    "Samsung Galaxy J3 2016",
    "Samsung Galaxy J3 2017",
    "Samsung Galaxy J3 Pro",
    "Samsung Galaxy J4",
    "Samsung Galaxy J4 Core",
    "Samsung Galaxy J4 Plus",
    "Samsung Galaxy J5 2015",
    "Samsung Galaxy J5 2016",
    "Samsung Galaxy J5 2017",
    "Samsung Galaxy J5 Prime",
    "Samsung Galaxy J5 Pro",
    "Samsung Galaxy J6",
    "Samsung Galaxy J6 Plus",
    "Samsung Galaxy J7 2015",
    "Samsung Galaxy J7 2016",
    "Samsung Galaxy J7 2017",
    "Samsung Galaxy J7 Duo",
    "Samsung Galaxy J7 Max",
    "Samsung Galaxy J7 Next",
    "Samsung Galaxy J7 Prime",
    "Samsung Galaxy J7 Pro",
    "Samsung Galaxy J7 Plus",
    "Samsung Galaxy J8 2018",
    "Samsung Galaxy M01",
    "Samsung Galaxy M01s",
    "Samsung Galaxy M01 Core",
    "Samsung Galaxy M02",
    "Samsung Galaxy M02S",
    "Samsung Galaxy M04",
    "Samsung Galaxy M10",
    "Samsung Galaxy M10s (No Sides)",
    "Samsung Galaxy M11",
    "Samsung Galaxy M12",
    "Samsung Galaxy M13 (4G)",
    "Samsung Galaxy M13 (5G)",
    "Samsung Galaxy M14 (4G)",
    "Samsung Galaxy M14 (5G)",
    "Samsung Galaxy M15 (5G)",
    "Samsung Galaxy M16 (5G)",
    "Samsung Galaxy M17 (5G)",
    "Samsung Galaxy M17e (5G)",
    "Samsung Galaxy M20",
    "Samsung Galaxy M21 (2020)",
    "Samsung Galaxy M21 (2021) (No Sides)",
    "Samsung Galaxy M22 (No Sides)",
    "Samsung Galaxy M30",
    "Samsung Galaxy M30S",
    "Samsung Galaxy M31",
    "Samsung Galaxy M31s",
    "Samsung Galaxy M3 Prime",
    "Samsung Galaxy M32 (4G)",
    "Samsung Galaxy M32 (5G)",
    "Samsung Galaxy M33 (5G)",
    "Samsung Galaxy M34 (5G)",
    "Samsung Galaxy M35 (5G)",
    "Samsung Galaxy M36 (5G)",
    "Samsung Galaxy M40",
    "Samsung Galaxy M42",
    "Samsung Galaxy M51",
    "Samsung Galaxy M52 (5G)",
    "Samsung Galaxy M53 (5G)",
    "Samsung Galaxy M55 (5G)",
    "Samsung Galaxy M56 (5G)",
    "Samsung Galaxy M62",
    "Samsung Galaxy Note 3",
    "Samsung Galaxy Note 3 Neo",
    "Samsung Galaxy Note 4",
    "Samsung Galaxy Note 5",
    "Samsung Galaxy Note 5 Edge",
    "Samsung Galaxy Note 8",
    "Samsung Galaxy Note 9",
    "Samsung Galaxy Note 9 Pro",
    "Samsung Galaxy Note 10",
    "Samsung Galaxy Note 10 Lite",
    "Samsung Galaxy Note 10 Plus",
    "Samsung Galaxy Note 20",
    "Samsung Galaxy Note 20 Ultra",
    "Samsung Galaxy On 6",
    "Samsung Galaxy On 8",
    "Samsung Galaxy On Next",
    "Samsung Galaxy On5 2015",
    "Samsung Galaxy On5 2016",
    "Samsung Galaxy On5 Pro",
    "Samsung Galaxy On7 2015",
    "Samsung Galaxy On7 2016",
    "Samsung Galaxy On7 Pro",
    "Samsung Galaxy On8 2018",
    "Samsung Galaxy S5",
    "Samsung Galaxy S5 Mini",
    "Samsung Galaxy S6",
    "Samsung Galaxy S6 Edge",
    "Samsung Galaxy S6 Edge Plus",
    "Samsung Galaxy S7",
    "Samsung Galaxy S7 Edge",
    "Samsung Galaxy S8",
    "Samsung Galaxy S8 Plus",
    "Samsung Galaxy S9",
    "Samsung Galaxy S9 Plus",
    "Samsung Galaxy S10 (4G)",
    "Samsung Galaxy S10 (5G)",
    "Samsung Galaxy S10 Lite",
    "Samsung Galaxy S10 Plus",
    "Samsung Galaxy S10E",
    "Samsung Galaxy S20",
    "Samsung Galaxy S20 FE",
    "Samsung Galaxy S20 Plus",
    "Samsung Galaxy S20 Ultra",
    "Samsung Galaxy S21 (5G)",
    "Samsung Galaxy S21 FE (5G)",
    "Samsung Galaxy S21 Plus",
    "Samsung Galaxy S21 Ultra (5G)",
    "Samsung Galaxy S22",
    "Samsung Galaxy S22 Plus",
    "Samsung Galaxy S22 Ultra",
    "Samsung Galaxy S23 (5G)",
    "Samsung Galaxy S23 FE (5G)",
    "Samsung Galaxy S23 Plus (5G)",
    "Samsung Galaxy S23 Ultra (5G)",
    "Samsung Galaxy S24 (5G)",
    "Samsung Galaxy S24 FE (5G)",
    "Samsung Galaxy S24 Plus (5G)",
    "Samsung Galaxy S24 Ultra (5G)",
    "Samsung Galaxy S25 (5G)",
    "Samsung Galaxy S25 FE (5G)",
    "Samsung Galaxy S25 Plus (5G)",
    "Samsung Galaxy S25 Edge (5G)",
    "Samsung Galaxy S25 Ultra (5G)",
    "Samsung Galaxy S26 (5G)",
    "Samsung Galaxy S26 Plus (5G)",
    "Samsung Galaxy S26 Ultra (5G)",
    "Samsung Galaxy Z Flip",
    "Samsung Galaxy Z Flip 3 (5G)",
    "Samsung Galaxy Z Flip 4 (5G)",
    "Samsung Galaxy Z Flip 5 (5G)",
    "Samsung Galaxy Z Flip 6 (5G)",
    "Samsung Galaxy Z Flip 7 (5G) (Only Bottom)",
    "Samsung Galaxy Z Fold",
    "Samsung Galaxy Z Fold 2",
    "Samsung Galaxy Z Fold 3 (5G)",
    "Samsung Galaxy Z Fold 4 (5G)",
    "Samsung Galaxy Z Fold 5 (5G)",
    "Samsung Galaxy Z Fold 6 (5G)",
    "Samsung Galaxy Z Fold 7 (5G)",
    "Samsung Galaxy XCover6 Pro (5G)"
  ],
  "Realme": [
    "Realme 1",
    "Realme 2",
    "Realme 2 Pro",
    "Realme 3",
    "Realme 3 Pro",
    "Realme 3i",
    "Realme 5",
    "Realme 5 Pro",
    "Realme 5i",
    "Realme 5s",
    "Realme 6",
    "Realme 6 Pro",
    "Realme 6i",
    "Realme 7",
    "Realme 7i",
    "Realme 7 Pro",
    "Realme 8 (4G)",
    "Realme 8 (5G)",
    "Realme 8 Pro",
    "Realme 8i",
    "Realme 8s",
    "Realme 9 (4G)",
    "Realme 9 (5G)",
    "Realme 9i (4G)",
    "Realme 9i (5G)",
    "Realme 9 Pro (5G)",
    "Realme 9 Pro Plus (5G)",
    "Realme 9 SE",
    "Realme 9 (5G) Speed Edition (Realme 9 SE)",
    "Realme 10 (4G)",
    "Realme 10 (5G)",
    "Realme 10 Pro (5G)",
    "Realme 10 Pro Plus (5G)",
    "Realme 11 (5G)",
    "Realme 11X (5G)",
    "Realme 11 Pro",
    "Realme 11 Pro Plus",
    "Realme 12 (5G)",
    "Realme 12x (5G)",
    "Realme 12 Plus (5G)",
    "Realme 12 Pro (5G)",
    "Realme 12 Pro Plus (5G)",
    "Realme 13 (5G)",
    "Realme 13 Plus (5G)",
    "Realme 13 Pro (5G)",
    "Realme 13 Pro Plus (5G)",
    "Realme 14T (5G)",
    "Realme 14X (5G)",
    "Realme 14 Pro (5G)",
    "Realme 14 Pro Lite (5G)",
    "Realme 14 Pro Plus (5G)",
    "Realme 15 (5G)",
    "Realme 15x (5G)",
    "Realme 15T (5G)",
    "Realme 15 Lite (5G)",
    "Realme 15 Pro (5G)",
    "Realme 16 (5G)",
    "Realme 16 Pro (5G)",
    "Realme 16 Pro Plus (5G)",
    "Realme C1",
    "Realme C2",
    "Realme C3",
    "Realme C11",
    "Realme C11 (2021)",
    "Realme C12",
    "Realme C15",
    "Realme C17",
    "Realme C20",
    "Realme C21",
    "Realme C21Y",
    "Realme C25",
    "Realme C25S",
    "Realme C25Y",
    "Realme C30",
    "Realme C30S",
    "Realme C31",
    "Realme C33",
    "Realme C35",
    "Realme C51",
    "Realme C53",
    "Realme C55",
    "Realme C61 (India)",
    "Realme C61 (Global)",
    "Realme C63 (4G)",
    "Realme C63 (5G)",
    "Realme C65 (5G)",
    "Realme C67 (4G)",
    "Realme C67 (5G)",
    "Realme C71 (4G) (India)",
    "Realme C71 (4G) (Global)",
    "Realme C73 (5G)",
    "Realme C75 (4G)",
    "Realme C75 (5G)",
    "Realme C83 (5G)",
    "Realme C85 (5G)",
    "Realme Narzo 10",
    "Realme Narzo 10A",
    "Realme Narzo 20",
    "Realme Narzo 20 Pro",
    "Realme Narzo 20A",
    "Realme Narzo 30 (4G)",
    "Realme Narzo 30 (5G)",
    "Realme Narzo 30 Pro (5G)",
    "Realme Narzo 30A",
    "Realme Narzo 50 (4G)",
    "Realme Narzo 50 (5G)",
    "Realme Narzo 50 Pro (5G)",
    "Realme Narzo 50i",
    "Realme Narzo 50i Prime",
    "Realme Narzo 50A",
    "Realme Narzo 50A Prime",
    "Realme Narzo 60 (5G)",
    "Realme Narzo 60x (5G)",
    "Realme Narzo 60 Pro (5G)",
    "Realme Narzo 70 (5G)",
    "Realme Narzo 70x (5G)",
    "Realme Narzo 70 Pro (5G)",
    "Realme Narzo 70 Turbo (5G)",
    "Realme Narzo 80x (5G)",
    "Realme Narzo 80 Lite (4G)",
    "Realme Narzo 80 Lite (5G)",
    "Realme Narzo 80 Pro (5G) (Only Back)",
    "Realme Narzo 90 (5G)",
    "Realme Narzo 90x (5G)",
    "Realme Narzo N53",
    "Realme Narzo N55",
    "Realme Narzo N61",
    "Realme Narzo N63",
    "Realme Narzo N65 (5G)",
    "Realme Note 50",
    "Realme Note 60",
    "Realme P1 (5G)",
    "Realme P1 Pro (5G)",
    "Realme P1 Speed (5G)",
    "Realme P2 Pro (5G)",
    "Realme P3 (5G)",
    "Realme P3X (5G)",
    "Realme P3 Pro (5G)",
    "Realme P3 Ultra (5G)",
    "Realme P4 (5G)",
    "Realme P4x (5G)",
    "Realme P4 Pro (5G)",
    "Realme P4 Power (5G)",
    "Realme U1",
    "Realme X",
    "Realme XT",
    "Realme X Lite",
    "Realme X2",
    "Realme X2 Pro",
    "Realme X3",
    "Realme X3 Super Zoom",
    "Realme X7",
    "Realme X7 Pro",
    "Realme X7 Max (5G)",
    "Realme X50 Pro (5G)",
    "Realme GT (5G)",
    "Realme GT Master Edition (5G)",
    "Realme GT 2 (5G)",
    "Realme GT 2 Pro",
    "Realme GT 6 (5G)",
    "Realme GT 6T (5G)",
    "Realme GT 7 (5G)",
    "Realme GT 7T (5G)",
    "Realme GT 7 Pro (5G)",
    "Realme GT 8 Pro (5G)",
    "Realme GT Neo 2 (5G)",
    "Realme GT Neo 3 (5G)",
    "Realme GT Neo 3T (5G)"
  ],
  "Poco": [
    "Poco C3",
    "Poco C31",
    "Poco C50",
    "Poco C51",
    "Poco C55",
    "Poco C61",
    "Poco C65",
    "Poco C71",
    "Poco C75",
    "Poco F1",
    "Poco F2 Pro",
    "Poco F3",
    "Poco F3 GT (5G)",
    "Poco F4 (5G)",
    "Poco F4 GT",
    "Poco F5 (5G)",
    "Poco F5 Pro (5G)",
    "Poco F6 (5G)",
    "Poco F7 (5G)",
    "Poco X2",
    "Poco X3",
    "Poco X3 Pro",
    "Poco X3 NFC",
    "Poco X4 GT (5G)",
    "Poco X4 Pro (5G)",
    "Poco X5 (5G)",
    "Poco X5 Pro (5G)",
    "Poco X6 (5G)",
    "Poco X6 Pro (5G)",
    "Poco X6 Neo (5G)",
    "Poco X7 (5G)",
    "Poco X7 Pro (5G)",
    "Poco X8 Pro (5G)",
    "Poco X8 Pro Max (5G) (Only Back)",
    "Poco M2",
    "Poco M2 Pro",
    "Poco M3",
    "Poco M3 Pro (5G)",
    "Poco M4 (5G) (Only Back)",
    "Poco M4 Pro (4G)",
    "Poco M4 Pro (5G)",
    "Poco M5 (Only Back)",
    "Poco M6 (5G)",
    "Poco M6 Pro (5G)",
    "Poco M6 Plus (5G)",
    "Poco M7 (5G)",
    "Poco M7 Plus (5G) (Only Back)",
    "Poco M7 Pro (5G)"
  ],
  "Xiaomi Redmi": [
    "Xiaomi Mi Play",
    "Xiaomi Mi A1",
    "Xiaomi Mi A2",
    "Xiaomi Mi A2 Lite",
    "Xiaomi Mi A3",
    "Xiaomi Mi 3",
    "Xiaomi Mi 4",
    "Xiaomi Mi 4S",
    "Xiaomi Mi 5",
    "Xiaomi Mi 6",
    "Xiaomi Mi 8",
    "Xiaomi Mi 9",
    "Xiaomi Mi 9 Lite",
    "Xiaomi Mi 9T",
    "Xiaomi Mi 10 (4G)",
    "Xiaomi Mi 10i",
    "Xiaomi Mi 10T (5G)",
    "Xiaomi Mi 10T Lite",
    "Xiaomi Mi 11 (5G)",
    "Xiaomi Mi 11i (5G)",
    "Xiaomi Mi 11i Hypercharge (5G)",
    "Xiaomi Mi 11X",
    "Xiaomi Mi 11X Pro",
    "Xiaomi Mi 11T Pro",
    "Xiaomi Mi 11 Lite",
    "Xiaomi Mi 11 Lite NE",
    "Xiaomi Mi 11 Ultra",
    "Xiaomi Mi 12 Lite (Only Back)",
    "Xiaomi Mi 12 Pro (5G)",
    "Xiaomi Mi 12 Lite (No Sides)",
    "Xiaomi Mi 12s Ultra (5G)",
    "Xiaomi Mi 13T (5G)",
    "Xiaomi Mi 13 Lite (5G)",
    "Xiaomi Mi 13 Pro (5G)",
    "Xiaomi Mi 14 (5G)",
    "Xiaomi MI 14 Civi",
    "Xiaomi MI 14 Ultra (5G)",
    "Xiaomi Mi 15 (5G)",
    "Xiaomi Mi 15 Ultra (5G)",
    "Xiaomi Mi 17 (5G)",
    "Xiaomi Mi CC9",
    "Xiaomi Mi Max",
    "Xiaomi Mi Max 2",
    "Xiaomi Mi Mix 2",
    "Xiaomi Mi Note 10",
    "Xiaomi Mi Note 10 Lite",
    "Redmi A1",
    "Redmi A1 Plus 2022",
    "Redmi A2",
    "Redmi A3",
    "Redmi A3x",
    "Redmi A4 (5G)",
    "Redmi A5",
    "Redmi S2",
    "Redmi Y1",
    "Redmi Y1 Lite",
    "Redmi Y2",
    "Redmi Y3",
    "Redmi 3s",
    "Redmi 3s Prime",
    "Redmi 4",
    "Redmi 4A",
    "Redmi 4X",
    "Redmi 4 Pro",
    "Redmi 5",
    "Redmi 5A",
    "Redmi 5 Plus",
    "Redmi 6",
    "Redmi 6A",
    "Redmi 6 Pro",
    "Redmi 7",
    "Redmi 7A",
    "Redmi 8",
    "Redmi 8A",
    "Redmi 8T (Only Back)",
    "Redmi 8A Dual",
    "Redmi 9",
    "Redmi 9 Activ",
    "Redmi 9 Power",
    "Redmi 9 Prime",
    "Redmi 9A",
    "Redmi 9i",
    "Redmi 9i Sport",
    "Redmi 9T",
    "Redmi 10",
    "Redmi 10A",
    "Redmi 10A Sport",
    "Redmi 10C",
    "Redmi 10x",
    "Redmi 10 Power",
    "Redmi 10 Prime",
    "Redmi 11 Prime (4G)",
    "Redmi 11 Prime (5G)",
    "Redmi 12 (4G)",
    "Redmi 12 (5G)",
    "Redmi 12C",
    "Redmi 13 (5G)",
    "Redmi 13C (4G)",
    "Redmi 13C (5G)",
    "Redmi 14C (4G)",
    "Redmi 14C (5G)",
    "Redmi 15 (5G)",
    "Redmi 15C (5G)",
    "Redmi Go",
    "Redmi K20",
    "Redmi K20 Pro",
    "Redmi K50i (5G)",
    "Redmi Note 2",
    "Redmi Note 3",
    "Redmi Note 4",
    "Redmi Note 5",
    "Redmi Note 5A",
    "Redmi Note 5 Pro",
    "Redmi Note 6 Pro",
    "Redmi Note 7",
    "Redmi Note 7s",
    "Redmi Note 7 Pro",
    "Redmi Note 8",
    "Redmi Note 8 Pro",
    "Redmi Note 9",
    "Redmi Note 9 Pro",
    "Redmi Note 9 Pro Max",
    "Redmi Note 9s",
    "Redmi Note 9T (4G)",
    "Redmi Note 9T (5G) (Only Back)",
    "Redmi Note 10",
    "Redmi Note 10s",
    "Redmi Note 10 Lite",
    "Redmi Note 10T (5G)",
    "Redmi Note 10 Pro",
    "Redmi Note 10 Pro Max",
    "Redmi Note 11",
    "Redmi Note 11S",
    "Redmi Note 11 SE",
    "Redmi Note 11T (5G)",
    "Redmi Note 11 Pro",
    "Redmi Note 11 Pro Plus (5G)",
    "Redmi Note 12 (4G)",
    "Redmi Note 12 (5G)",
    "Redmi Note 12 Pro (5G)",
    "Redmi Note 12 Pro Plus (5G)",
    "Redmi Note 13 (5G)",
    "Redmi Note 13 Pro (5G)",
    "Redmi Note 13 Pro Plus (5G)",
    "Redmi Note 14 (5G)",
    "Redmi Note 14 Pro (5G)",
    "Redmi Note 14 Pro Plus (5G)",
    "Redmi Note 15 (5G)",
    "Redmi Note 15 Pro (5G)",
    "Redmi Note 15 Pro Plus (5G)",
    "Black Shark 2 (Only Back)"
  ],
  "Oppo": [
    "Oppo A1k",
    "Oppo A3s",
    "Oppo A3 (5G)",
    "Oppo A3x (4G)",
    "Oppo A3x (5G)",
    "Oppo A3 Pro (5G)",
    "Oppo A5",
    "Oppo A5S",
    "Oppo A5 2020",
    "Oppo A5 (5G)",
    "Oppo A5X (5G)",
    "Oppo A5 Pro (5G)",
    "Oppo A6x (5G)",
    "Oppo A6 Pro (4G)",
    "Oppo A6 Pro (5G)",
    "Oppo A7",
    "Oppo A9",
    "Oppo A9 2020",
    "Oppo A11K",
    "Oppo A12",
    "Oppo A15",
    "Oppo A15s",
    "Oppo A16",
    "Oppo A16E",
    "Oppo A16K",
    "Oppo A17",
    "Oppo A17K",
    "Oppo A18",
    "Oppo A31",
    "Oppo A33",
    "Oppo A37",
    "Oppo A38",
    "Oppo A51",
    "Oppo A52",
    "Oppo A53",
    "Oppo A53s 5G",
    "Oppo A54",
    "Oppo A55",
    "Oppo A57 (3G)",
    "Oppo A57 (4G)",
    "Oppo A57 (5G)",
    "Oppo A58 (4G)",
    "Oppo A59 (5G)",
    "Oppo A60",
    "Oppo A71",
    "Oppo A73",
    "Oppo A74 (5G)",
    "Oppo A76",
    "Oppo A77s",
    "Oppo A77 (4G)",
    "Oppo A78 (4G)",
    "Oppo A78 (5G)",
    "Oppo A79 (5G)",
    "Oppo A83",
    "Oppo A91",
    "Oppo A92 (Only Back)",
    "Oppo A93",
    "Oppo A94",
    "Oppo A95 (5G)",
    "Oppo A96",
    "Oppo F1",
    "Oppo F1S",
    "Oppo F1 Plus",
    "Oppo F3",
    "Oppo F3 Plus",
    "Oppo F5",
    "Oppo F7",
    "Oppo F9",
    "Oppo F9 Pro",
    "Oppo F11",
    "Oppo F11 Pro",
    "Oppo F15",
    "Oppo F17",
    "Oppo F17 Pro",
    "Oppo F19",
    "Oppo F19s",
    "Oppo F19 Pro",
    "Oppo F19 Pro Plus",
    "Oppo F21 Pro (4G)",
    "Oppo F21 Pro (5G)",
    "Oppo F21s Pro (4G)",
    "Oppo F21s Pro (5G)",
    "Oppo F23 (5G)",
    "Oppo F25 Pro (5G)",
    "Oppo F27 (5G)",
    "Oppo F27 Pro Plus (5G)",
    "Oppo F29 (5G)",
    "Oppo F29 Pro (5G)",
    "Oppo F31 (5G)",
    "Oppo F31 Pro (5G)",
    "Oppo F31 Pro Plus (5G)",
    "Oppo F33 (5G)",
    "Oppo F33 Pro (5G)",
    "Oppo Find N",
    "Oppo Find N2 (5G) (Only Back)",
    "Oppo Find N2 Flip (5G) (Only Back)",
    "Oppo Find N3 Flip (5G)",
    "Oppo Find X",
    "Oppo Find X2",
    "Oppo Find X5 Pro (5G) (Only Back)",
    "Oppo Find X8 (5G)",
    "Oppo Find X8 Pro (5G)",
    "Oppo Find X9 (5G)",
    "Oppo Find X9 Pro (5G)",
    "Oppo K1",
    "Oppo K3",
    "Oppo K10 (4G)",
    "Oppo K10 (5G)",
    "Oppo K12x (5G)",
    "Oppo K13 (5G)",
    "Oppo K13x (5G)",
    "Oppo K13 Turbo (5G)",
    "Oppo K14 (5G)",
    "Oppo K14x (5G)",
    "Oppo Neo 5",
    "Oppo Neo 7",
    "Oppo R7",
    "Oppo R9",
    "Oppo R11",
    "Oppo R11S",
    "Oppo R15",
    "Oppo R15 Pro",
    "Oppo R17",
    "Oppo R17 Pro",
    "Oppo Reno",
    "Oppo Reno 2",
    "Oppo Reno 2f",
    "Oppo Reno 2Z",
    "Oppo Reno 3",
    "Oppo Reno 3 Pro",
    "Oppo Reno 4",
    "Oppo Reno 4 Pro",
    "Oppo Reno 5 (4G)",
    "Oppo Reno 5 (5G)",
    "Oppo Reno 5Z (5G)",
    "Oppo Reno 5 Lite",
    "Oppo Reno 5 Pro",
    "Oppo Reno 6",
    "Oppo Reno 6 Pro (5G)",
    "Oppo Reno 7 (5G)",
    "Oppo Reno 7 Pro (5G)",
    "Oppo Reno 8 (5G)",
    "Oppo Reno 8T (4G)",
    "Oppo Reno 8T (5G)",
    "Oppo Reno 8 Pro (5G)",
    "Oppo Reno 10 (5G)",
    "Oppo Reno 10 Pro (5G)",
    "Oppo Reno 10 Pro Plus (5G)",
    "Oppo Reno 10X Zoom",
    "Oppo Reno 11 (5G)",
    "Oppo Reno 11 Pro (5G)",
    "Oppo Reno 12 (5G)",
    "Oppo Reno 12F (5G)",
    "Oppo Reno 12 Pro (5G)",
    "Oppo Reno 13 (5G)",
    "Oppo Reno 13 Pro (5G)",
    "Oppo Reno 14 (5G)",
    "Oppo Reno 14 Pro (5G)",
    "Oppo Reno 15 (5G)",
    "Oppo Reno 15C (5G)",
    "Oppo Reno 15F (5G)",
    "Oppo Reno 15 Pro (5G)",
    "Oppo Reno 15 Pro Mini (5G)"
  ],
  "Vivo": [
    "Vivo T1",
    "Vivo T1 44W SNAPDRAGON 680",
    "Vivo T1 5G",
    "Vivo T1 Pro 5G",
    "Vivo T1X",
    "Vivo T2 (5G)",
    "Vivo T2X (5G)",
    "Vivo T2 Pro (5G)",
    "Vivo T3 (5G)",
    "Vivo T3x (5G)",
    "Vivo T3 Lite (5G)",
    "Vivo T3 Pro (5G)",
    "Vivo T3 Ultra (5G)",
    "Vivo T4 (5G)",
    "Vivo T4R (5G)",
    "Vivo T4x (5G)",
    "Vivo T4 Pro (5G)",
    "Vivo T4 Lite (5G)",
    "Vivo T4 Ultra (5G)",
    "Vivo T5x (5G)",
    "Vivo T5 Pro (5G) (Only Back)",
    "Vivo Nex A",
    "Vivo Nex S",
    "Vivo S1",
    "Vivo S1 Pro",
    "Vivo S5",
    "Vivo S7 5G",
    "Vivo S9",
    "Vivo S12",
    "Vivo S12 Pro",
    "Vivo U1",
    "Vivo U10",
    "Vivo U20",
    "Vivo V3",
    "Vivo V3 Max",
    "Vivo V5",
    "Vivo V5 Plus",
    "Vivo V5S",
    "Vivo V7",
    "Vivo V7 Plus",
    "Vivo V9",
    "Vivo V9 Pro",
    "Vivo V9 Youth",
    "Vivo V11",
    "Vivo V11 Pro",
    "Vivo V15",
    "Vivo V15s",
    "Vivo V15 Pro",
    "Vivo V17",
    "Vivo V17 Pro",
    "Vivo V19",
    "Vivo V20",
    "Vivo V20 Pro",
    "Vivo V20 SE",
    "Vivo V21",
    "Vivo V21 (5G)",
    "Vivo V21e (4G)",
    "Vivo V21e (5G)",
    "Vivo V23 (5G)",
    "Vivo V23e (5G)",
    "Vivo V23 Pro (5G)",
    "Vivo V25 (5G)",
    "Vivo V25 Pro (5G)",
    "Vivo V27 (5G)",
    "Vivo V27e",
    "Vivo V27 Pro (5G)",
    "Vivo V29 (5G)",
    "Vivo V29e (5G)",
    "Vivo V29 Pro (5G)",
    "Vivo V30 (5G)",
    "Vivo V30e (5G)",
    "Vivo V30 Pro (5G)",
    "Vivo V40 (5G)",
    "Vivo V40e (5G)",
    "Vivo V40 Lite (5G)",
    "Vivo V40 Pro (5G)",
    "Vivo V50 (5G)",
    "Vivo V50e (5G)",
    "Vivo V50 Lite",
    "Vivo V60 (5G)",
    "Vivo V60e (5G)",
    "Vivo V70 (5G)",
    "Vivo V70 FE (5G)",
    "Vivo V70 Elite (5G)",
    "Vivo X Note",
    "Vivo X9s",
    "Vivo X9 Plus",
    "Vivo X21",
    "Vivo X21i",
    "Vivo X21s",
    "Vivo X27",
    "Vivo X30 Pro",
    "Vivo X50",
    "Vivo X50 Pro",
    "Vivo X60",
    "Vivo X60 Pro",
    "Vivo X60 Pro Plus",
    "Vivo X70 Pro",
    "Vivo X70 Pro Plus 5G",
    "Vivo X80 5G",
    "Vivo X80 Pro 5G",
    "Vivo X90",
    "Vivo X90 Pro",
    "Vivo X100 (5G)",
    "Vivo X100 Pro (5G)",
    "Vivo X200 (5G)",
    "Vivo X200T (5G)",
    "Vivo X200 FE (5G)",
    "Vivo X200 Pro (5G)",
    "Vivo X300 (5G)",
    "Vivo X300 FE (5G)",
    "Vivo X300 Pro (5G)",
    "Vivo X300 Ultra (5G)",
    "Vivo X Fold 3 Pro (5G) (Only Back)",
    "Vivo X Fold 5 (5G) (Only Back)",
    "Vivo Y01",
    "Vivo Y1s",
    "Vivo Y1s 2020",
    "Vivo Y02",
    "Vivo Y02T",
    "Vivo Y02s 2022",
    "Vivo Y3",
    "Vivo Y3s",
    "Vivo Y11",
    "Vivo Y11s",
    "Vivo Y12",
    "Vivo Y12G",
    "Vivo Y12S",
    "Vivo Y15",
    "Vivo Y15C",
    "Vivo Y15s",
    "Vivo Y16",
    "Vivo Y17",
    "Vivo Y17s",
    "Vivo Y18",
    "Vivo Y18e",
    "Vivo Y19 (4G)",
    "Vivo Y19 (5G)",
    "Vivo Y19e",
    "Vivo Y19s (4G)",
    "Vivo Y19s (5G)",
    "Vivo Y20",
    "Vivo Y20s",
    "Vivo Y20T",
    "Vivo Y20A",
    "Vivo Y20i",
    "Vivo Y20G",
    "Vivo Y21",
    "Vivo Y21A 2021",
    "Vivo Y21T",
    "Vivo Y21E",
    "Vivo Y21G",
    "Vivo Y21 (2021)",
    "Vivo Y22 (2022)",
    "Vivo Y27",
    "Vivo Y28 (4G)",
    "Vivo Y28 (5G)",
    "Vivo Y28e (5G)",
    "Vivo Y28s (5G)",
    "Vivo Y29 (5G)",
    "Vivo Y30",
    "Vivo Y31",
    "Vivo Y31 2021",
    "Vivo Y31 (5G)",
    "Vivo Y31 Pro (5G)",
    "Vivo Y33T",
    "Vivo Y33S",
    "Vivo Y35 2022",
    "Vivo Y36",
    "Vivo Y39 (5G)",
    "Vivo Y50",
    "Vivo Y51",
    "Vivo Y51A",
    "Vivo Y51s",
    "Vivo Y51 Pro (5G)",
    "Vivo Y51L (No Sides)",
    "Vivo Y52s",
    "Vivo Y53",
    "Vivo Y53s",
    "Vivo Y53s 2021",
    "Vivo Y55 (No Sides)",
    "Vivo Y55 (2022)",
    "Vivo Y55L",
    "Vivo Y55s",
    "Vivo Y56 (5G)",
    "Vivo Y58 (5G)",
    "Vivo Y66",
    "Vivo Y69",
    "Vivo Y71",
    "Vivo Y71I",
    "Vivo Y72 (5G)",
    "Vivo Y73",
    "Vivo Y75 (4G)",
    "Vivo Y75 (5G)",
    "Vivo Y76 (5G) (Only Back)",
    "Vivo Y78 (5G) (Only Back)",
    "Vivo Y81",
    "Vivo Y83",
    "Vivo Y83 Pro",
    "Vivo Y85",
    "Vivo Y91",
    "Vivo Y91i",
    "Vivo Y93",
    "Vivo Y95",
    "Vivo Y100 (5G)",
    "Vivo Y100A",
    "Vivo Y200 (5G)",
    "Vivo Y200e (5G)",
    "Vivo Y200 Pro (5G)",
    "Vivo Y300 (5G)",
    "Vivo Y300 Plus (5G)",
    "Vivo Y400 (5G)",
    "Vivo Y400 Pro (5G)",
    "Vivo Z1 Pro",
    "Vivo Z1X",
    "Vivo Z10 (Only Back)"
  ],
  "iQOO": [
    "Vivo IQOO U1X",
    "Vivo IQOO Z1X",
    "Vivo IQOO Z3 (5G)",
    "Vivo IQOO Z5 (5G)",
    "Vivo IQOO Z6 (4G)",
    "Vivo IQOO Z6 (5G)",
    "Vivo IQOO Z6 Lite (5G)",
    "Vivo IQOO Z6 Pro (5G)",
    "Vivo IQOO Z7 (5G)",
    "Vivo iQOO Z7s (5G)",
    "Vivo IQOO Z7 Pro (5G)",
    "Vivo iQOO Z9 (5G)",
    "Vivo iQOO Z9 Lite (5G)",
    "Vivo iQOO Z9x (5G)",
    "Vivo iQOO Z9s (5G)",
    "Vivo iQOO Z9s Pro (5G)",
    "Vivo iQOO Z9 Turbo (5G)",
    "Vivo iQOO Z10 (5G)",
    "Vivo iQOO Z10X (5G)",
    "Vivo iQOO Z10R (5G)",
    "Vivo iQOO Z10 Lite (5G)",
    "Vivo iQOO Z11x (5G)",
    "Vivo IQOO Neo",
    "Vivo IQOO Neo Pro",
    "Vivo IQOO Neo 3 (No Sides)",
    "Vivo IQOO Neo 5",
    "Vivo IQOO Neo 6 (5G)",
    "Vivo IQOO Neo 7 (5G)",
    "Vivo IQOO Neo 7 Pro (5G)",
    "Vivo iQOO Neo 9 Pro (5G)",
    "Vivo iQOO Neo 10 (5G)",
    "Vivo iQOO Neo 10R (5G)",
    "Vivo IQOO 3 (5G)",
    "Vivo IQOO 7 (5G)",
    "Vivo IQOO 7 Legend (5G)",
    "Vivo IQOO 9 (5G)",
    "Vivo IQOO 9T (5G) (No Sides)",
    "Vivo IQOO 9 SE (5G)",
    "Vivo IQOO 9 Pro (5G)",
    "Vivo IQOO 11 (5G) (Only Back)",
    "Vivo iQOO 12 (5G)",
    "Vivo iQOO 13 (5G)",
    "Vivo iQOO 15 (5G)",
    "Vivo iQOO 15R (5G)"
  ],
  "Asus": [
    "Asus Rog 2",
    "Asus Rog 3",
    "Asus Rog Phone 5",
    "Asus Rog Phone 6 (5G)",
    "Asus Rog Phone 6 Pro (5G)",
    "Asus Rog Phone 7 (5G)",
    "Asus Rog Phone 7 Ultimate (5G)",
    "Asus Rog Phone 8 Pro (5G) (Only Back)",
    "Asus Zenfone Max Pro M1",
    "Asus Zenfone Max Pro M2",
    "Asus Zenfone Max M2 (No Sides)",
    "Asus Zenfone 5Z",
    "Asus Zenfone 6",
    "Asus Zenfone 6Z",
    "Asus Zenfone 8z (5G) (Only Back)"
  ],
  "Google": [
    "Google Pixel",
    "Google Pixel XL",
    "Google Pixel 1 XL",
    "Google Pixel 2",
    "Google Pixel 2 XL",
    "Google Pixel 3",
    "Google Pixel 3 XL",
    "Google Pixel 3A",
    "Google Pixel 3a XL",
    "Google Pixel 4",
    "Google Pixel 4 XL",
    "Google Pixel 4A",
    "Google Pixel 4A 5G",
    "Google Pixel 5",
    "Google Pixel 5A",
    "Google Pixel 6 (5G)",
    "Google Pixel 6A (5G)",
    "Google Pixel 6 Pro (5G)",
    "Google Pixel 7 (5G)",
    "Google Pixel 7A (5G)",
    "Google Pixel 7 Pro (5G)",
    "Google Pixel 8 (5G)",
    "Google Pixel 8A (5G)",
    "Google Pixel 8 Pro (5G)",
    "Google Pixel 9 (5G)",
    "Google Pixel 9A (5G)",
    "Google Pixel 9 Pro (5G)",
    "Google Pixel 9 Pro XL (5G)",
    "Google Pixel 9 Pro Fold (5G) (Only Back)",
    "Google Pixel 10 (5G)",
    "Google Pixel 10A (5G)",
    "Google Pixel 10 Pro (5G)",
    "Google Pixel 10 Pro XL (5G)",
    "Google Pixel 10 Pro Fold (5G)",
    "Google Pixel Fold (5G) (Only Back)"
  ],
  "Huawei Honor": [
    "Huawei Honor 3C",
    "Huawei Honor 4C",
    "Huawei Honor 4X",
    "Huawei Honor 5A",
    "Huawei Honor 5C",
    "Huawei Honor 5C Pro",
    "Huawei Honor 5X",
    "Huawei Honor 6",
    "Huawei Honor 6 Plus",
    "Huawei Honor 6A Pro",
    "Huawei Honor 6X",
    "Huawei Honor 7A",
    "Huawei Honor 7C",
    "Huawei Honor 7X",
    "Huawei Honor 8",
    "Huawei Honor 8A",
    "Huawei Honor 8A 2020",
    "Huawei Honor 8A Prime",
    "Huawei Honor 8 Lite",
    "Huawei Honor 8 Pro",
    "Huawei Honor 8C",
    "Huawei Honor 8X",
    "Huawei Honor 8X Max",
    "Huawei Honor 9",
    "Huawei Honor 9s (No Sides)",
    "Huawei Honor 9 Lite",
    "Huawei Honor 9I",
    "Huawei Honor 9N",
    "Huawei Honor 9X",
    "Huawei Honor 9X Lite",
    "Huawei Honor 9X Pro",
    "Huawei Honor Holly 2",
    "Huawei Honor P Lite",
    "Huawei Honor P20",
    "Huawei Honor P20 Lite",
    "Huawei Honor P20 Pro",
    "Huawei Honor P30",
    "Huawei Honor P30 Pro",
    "Huawei Honor P6",
    "Huawei Honor P8",
    "Huawei Honor Play",
    "Huawei Honor Play 7",
    "Huawei Honor Play 8A",
    "Huawei Honor Play 9A",
    "Huawei Honor V10",
    "Huawei Honor V20",
    "Huawei Honor 10",
    "Huawei Honor 10 Lite",
    "Huawei Honor 20",
    "Huawei Honor 20s",
    "Huawei Honor 20I",
    "Huawei Honor 20 Lite",
    "Huawei Honor 20 Pro",
    "Huawei Honor M20 Pro",
    "Huawei Honor 30",
    "Huawei Honor 30s",
    "Huawei Honor 30 Pro Plus",
    "Huawei Honor 70 (5G)",
    "Huawei Honor 90 (5G)",
    "Huawei Honor 90 Lite (5G)",
    "Huawei Honor 200 (5G)",
    "Huawei Honor 200 Lite (5G) (Only Back)",
    "Huawei Honor 200 Pro (5G) (Only Back)",
    "Huawei Honor 200 Smart (5G) (Only Back)",
    "Huawei Honor 400 (5G)",
    "Huawei Honor 400 Pro (5G)",
    "Huawei Honor Note 8",
    "Huawei Honor Note 10",
    "Huawei Honor View 10",
    "Huawei Honor View 20",
    "Huawei Mate S",
    "Huawei Mate 10",
    "Huawei Mate 10 Lite",
    "Huawei Mate 10 Pro",
    "Huawei Mate 20",
    "Huawei Mate 20 Lite",
    "Huawei Mate 20 Pro",
    "Huawei Mate 20x",
    "Huawei Mate 30 5G",
    "Huawei Mate 30 Pro",
    "Huawei Mate 40",
    "Huawei Mate 40 Pro",
    "Huawei Mate 50 Pro (No Sides)",
    "Huawei Mate 50 Rs (No Sides)",
    "Huawei Mate 50E (No Sides)",
    "Huawei Nova",
    "Huawei Nova Lite",
    "Huawei Nova Youth",
    "Huawei Nova 2",
    "Huawei Nova 2i",
    "Huawei Nova 2s",
    "Huawei Nova 2 Plus",
    "Huawei Nova 3",
    "Huawei Nova 3E",
    "Huawei Nova 3i",
    "Huawei Nova 4",
    "Huawei Nova 4E",
    "Huawei Nova 5",
    "Huawei Nova 5i",
    "Huawei Nova 5T",
    "Huawei Nova 5 Pro",
    "Huawei Nova 5i Pro",
    "Huawei Nova 6 SE",
    "Huawei Nova 7",
    "Huawei Nova 7 5G",
    "Huawei Nova 7 5G 2020",
    "Huawei Nova 7 Pro 5G",
    "Huawei Nova 7 SE",
    "Huawei Nova 7i",
    "Huawei Nova 8 5G",
    "Huawei Nova 8 SE",
    "Huawei Nova 8 Pro",
    "Huawei Nova 9",
    "Huewei Nova 9 SE (No Sides)",
    "Huawei Y9A",
    "Huawei Nova Y9A",
    "Huawei Nova 9 Pro",
    "Huawei Nova 10 SE",
    "Huawei Nova Y60 (No Sides)",
    "Huawei Nova Y70",
    "Huawei Nova Y70 Plus",
    "Huawei Nova Y90",
    "Huewei P Smart 2019",
    "Huewei P9",
    "Huewei P9 Lite",
    "Huewei P9 Plus",
    "Huewei G9 Lite/GR3",
    "Huewei P10",
    "Huewei P10 Lite",
    "Huewei P10 Plus",
    "Huewei P20",
    "Huewei P20 Lite",
    "Huewei P20 Pro",
    "Huewei P30",
    "Huewei P30 Lite",
    "Huewei P30 Pro",
    "Huewei P40 Lite",
    "Huewei P40",
    "Huewei P40 Pro",
    "Huewei P40 Pro Plus (No Sides)",
    "Huewei P50",
    "Huewei P50 Pro",
    "Huawei P60",
    "Huawei P60 Pro",
    "Huewei Y5 2018",
    "Huewei Y5 Lite 2018",
    "Huewei Y5 Prime 2018",
    "Huewei Y6 2018",
    "Huewei Y6 2019",
    "Huewei Y6s 2019",
    "Huewei Y6P 2020",
    "Huewei Y6 Prime",
    "Huewei Y6 Prime 2018",
    "Huewei Y6 Prime 2019",
    "Huewei Y6 Pro 2019",
    "Huewei Y7 (2019)",
    "Huewei Y7A",
    "Huewei Y7 Prime",
    "Huewei Y7 Prime 2018",
    "Huewei Y7 Prime 2019",
    "Huewei Y7 Prime Pro 2019",
    "Huewei Y8s (No Sides)",
    "Huewei Y9 2018",
    "Huewei Y9 2019",
    "Huewei Y9s",
    "Huewei Y9 Prime 2019",
    "Honor 10X Lite",
    "Honor 50",
    "Honor 50 Lite",
    "Huewei Honor 50",
    "Huewei Honor X7",
    "Huewei Honor X8",
    "Huewei Honor X9a (5G)",
    "Huewei Honor X9b (5G)",
    "Huawei Honor X9c (5G)",
    "Huawei Honor X9d (5G)",
    "Huewei Honor 9C (No Sides)",
    "Huewei Honor 90 (No Sides)",
    "Huewei Honor Magic 4 Lite",
    "Huewei Honor Magic 4 Pro",
    "Huewei Honor V9",
    "Huewei Honor V10",
    "Huewei L09/L19/L29",
    "Huawei Enjoy 7s",
    "Huawei Enjoy 8",
    "Huawei Enjoy 8 Plus",
    "Huawei Enjoy 8E Youth",
    "Huawei Enjoy 9 Plus",
    "Huawei Enjoy 9E",
    "Huawei Enjoy 10 Plus",
    "Huawei Enjoy 20 Pro",
    "Huawei Enjoy Z 5G"
  ],
  "Motorola": [
    "Motorola Moto C",
    "Motorola Moto C Plus",
    "Motorola Moto E",
    "Motorola Moto E3 Power",
    "Motorola Moto E4",
    "Motorola Moto E4 Plus",
    "Motorola Moto E5 (Only Back)",
    "Motorola Moto E5 Plus",
    "Motorola Moto E7 Power",
    "Motorola Moto E13",
    "Motorola Moto E22s",
    "Motorola Moto E32 (Only Back)",
    "Motorola Moto E32S (Only Back)",
    "Motorola Moto E40 (Only Back)",
    "Motorola Moto G",
    "Motorola Moto G (5G)",
    "Motorola Moto G Turbo",
    "Motorola Moto G Power (2022) (Only Back)",
    "Motorola Moto G Power (2025) (Only Back)",
    "Motorola Moto G Fast (Only Back)",
    "Motorola Moto G Fast (2020) (Only Back)",
    "Motorola Moto G Pure (Only Back)",
    "Motorola Moto G Stylus (Only Back)",
    "Motorola Moto G Stylus (2021) (Only Back)",
    "Motorola Moto G Stylus (5G) (Only Back)",
    "Motorola Moto G Stylus (5G) (2022) (Only Back)",
    "Motorola Moto G Play (2021)",
    "Motorola Moto G2",
    "Motorola Moto G3",
    "Motorola Moto G4",
    "Motorola Moto G4 Play",
    "Motorola Moto G4 Plus",
    "Motorola Moto G5",
    "Motorola Moto G05",
    "Motorola Moto G5 Plus",
    "Motorola Moto G5S",
    "Motorola Moto G5S Plus",
    "Motorola Moto G06 Power",
    "Motorola Moto G6",
    "Motorola Moto G6 Play",
    "Motorola Moto G7",
    "Motorola Moto G8 Power (Only Back)",
    "Motorola Moto G8 Power Lite (Only Back)",
    "Motorola Moto G8 Plus (Only Back)",
    "Motorola Moto G9 (Only Back)",
    "Motorola Moto G9 Power (Only Back)",
    "Motorola Moto G10 Power (Only Back)",
    "Motorola Moto G14 (Only Back)",
    "Motorola Moto G22",
    "Motorola Moto G24 Power (Only Back)",
    "Motorola Moto G30 (Only Back)",
    "Motorola Moto G31 (Only Back)",
    "Motorola Moto G32",
    "Motorola Moto G34 (5G)",
    "Motorola Moto G35 (5G)",
    "Motorola Moto G40 Fusion",
    "Motorola Moto G42 (Only Back)",
    "Motorola Moto G45 (5G)",
    "Motorola Moto G51 (5G) (Only Back)",
    "Motorola Moto G52",
    "Motorola Moto G54 (5G)",
    "Motorola Moto G57 Power (5G)",
    "Motorola Moto G60",
    "Motorola Moto G62 (5G)",
    "Motorola Moto G64 (5G)",
    "Motorola Moto G67 Power (5G)",
    "Motorola Moto G71 (5G)",
    "Motorola Moto G72 (5G) (Only Back)",
    "Motorola Moto G73 (5G)",
    "Motorola Moto G82 (5G) (Only Back)",
    "Motorola Moto G84 (5G)",
    "Motorola Moto G85 (5G)",
    "Motorola Moto G86 Power (5G)",
    "Motorola Moto G96 (5G)",
    "Motorola Moto M",
    "Motorola Moto X Force",
    "Motorola Moto X Play",
    "Motorola Moto X Style",
    "Motorola Moto X2",
    "Motorola Moto X3",
    "Motorola Moto X4",
    "Motorola Moto Z",
    "Motorola Moto Z Play",
    "Motorola Moto Z2 Play",
    "Motorola Moto Z3 Play",
    "Motorola Moto One",
    "Motorola Moto One Power",
    "Motorola Moto One Action",
    "Motorola Moto One Fusion Plus",
    "Motorola Moto One Macro (Only Back)",
    "Motorola Moto One (5G) (Only Back)",
    "Motorola Moto One (5G) Ace (Only Back)",
    "Motorola Moto One Hyper (Only Back)",
    "Motorola Moto Edge (Only Back)",
    "Motorola Moto Edge Plus (Only Back)",
    "Motorola Moto Edge X30 (5G) (Only Back)",
    "Motorola Moto Edge 20 (5G)",
    "Motorola Moto Edge 20 Fusion",
    "Motorola Moto Edge 20 Pro",
    "Motorola Moto Edge 30",
    "Motorola Moto Edge 30 Pro (Only Back)",
    "Motorola Moto Edge 30 Fusion (5G)",
    "Motorola Moto Edge 30 Ultra (5G)",
    "Motorola Moto Edge 40 (5G)",
    "Motorola Moto Edge 40 Neo (5G)",
    "Motorola Moto Edge 40 Pro (5G) (Only Back)",
    "Motorola Moto Edge 50 (5G)",
    "Motorola Moto Edge 50 Pro (5G)",
    "Motorola Moto Edge 50 Neo (5G)",
    "Motorola Moto Edge 50 Fusion (5G)",
    "Motorola Moto Edge 50 Ultra (5G)",
    "Motorola Moto Edge 60 (5G) (Only Back)",
    "Motorola Moto Edge 60 Pro (5G)",
    "Motorola Moto Edge 60 Fusion (5G)",
    "Motorola Moto Edge 60 Stylus (5G) (Only Back)",
    "Motorola Moto Edge 70 (5G)",
    "Motorola Moto Edge 70 Pro (5G)",
    "Motorola Moto Edge 70 Fusion (5G)",
    "Motorola Moto Razr (5G)",
    "Motorola Moto Razr 40 (5G)",
    "Motorola Moto Razr 40 Ultra (5G) (Only Back)",
    "Motorola Moto Razr 60 (5G) (Only Back)",
    "Motorola Moto Signature (5G) (Only Back)"
  ],
  "Nothing /CMF Phone": [
    "Nothing Phone 1",
    "Nothing Phone 2",
    "Nothing Phone 2a",
    "Nothing Phone 3",
    "Nothing Phone 3a",
    "Nothing Phone 3a Pro",
    "Nothing Phone 3a Lite",
    "Nothing Phone 4a",
    "Nothing Phone 4a Pro",
    "CMF Phone 1 (5G)",
    "CMF Phone 2 Pro (5G)"
  ],
  "Ai+": [
    "Ai+ Nova (5G)"
  ],
  "Nokia": [
    "Nokia 1",
    "Nokia 1TA",
    "Nokia 2",
    "Nokia 2TA",
    "Nokia 2.1 (2018)",
    "Nokia 2.4",
    "Nokia 3",
    "Nokia 3TA",
    "Nokia 3.1",
    "Nokia 3.1 Plus TA",
    "Nokia 3.2 TA",
    "Nokia 3.4",
    "Nokia 4",
    "Nokia 4.2",
    "Nokia 5",
    "Nokia 5TA",
    "Nokia 5.1 Plus TA",
    "Nokia 5.3",
    "Nokia 5.4",
    "Nokia 6 2018 TA (No Sides)",
    "Nokia 6.1 2018",
    "Nokia 6.1 Plus 2018",
    "Nokia 6.1 Plus TA",
    "Nokia 6.2",
    "Nokia 7 Plus TA",
    "Nokia 7.1 TA",
    "Nokia 7.2",
    "Nokia 7.2 TA",
    "Nokia 8",
    "Nokia 8 TA",
    "Nokia 8.1",
    "Nokia 8.1 TA",
    "Nokia 9",
    "Nokia 9 Pureview TA-1087",
    "Nokia 1020",
    "Nokia C01 Plus",
    "Nokia C3 (2020)",
    "Nokia C12 (Only Back)",
    "Nokia C12 Pro",
    "Nokia C21 Plus",
    "Nokia C22",
    "Nokia C30",
    "Nokia C31 (No Sides)",
    "Nokia C32",
    "Nokia G10 (No Sides)",
    "Nokia G20 (No Sides)",
    "Nokia G21 (Only Back)",
    "Nokia G42 (5G)",
    "Nokia X20 (5G) (Only Back)",
    "Nokia X100 5G (Only Back)"
  ],
  "Infinix": [
    "Infinix Hot S3X",
    "Infinix Hot 4",
    "Infinix Hot 4 Pro",
    "Infinix Hot 5 (No Sides)",
    "Infinix Hot 6",
    "Infinix Hot 6 Pro",
    "Infinix Hot 6x",
    "Infinix Hot 7 (No Sides)",
    "Infinix Hot 7 Pro",
    "Infinix Hot 8",
    "Infinix Hot 8 Lite (No Sides)",
    "Infinix Hot 9",
    "Infinix Hot 9 Play",
    "Infinix Hot 9 Pro (No Sides)",
    "Infinix Hot 10",
    "Infinix Hot 10T (No Sides)",
    "Infinix Hot 10 Lite (No Sides)",
    "Infinix Hot 10s",
    "Infinix Hote 10s",
    "Infinix Hot 10 Play",
    "Infinix Hot 11",
    "Infinix Hot 11 2022 (No Sides)",
    "Infinix Hot 11 Play",
    "Infinix Hote 11 Play (No Sides)",
    "Infinix Hot 11s",
    "Infinix Hot 12",
    "Infinix Hot 12 Pro (No Sides)",
    "Infinix Hot 12 Play (No Sides)",
    "Infinix Hot 12i (No Sides)",
    "Infinix Hot 12 Pro Play (No Sides)",
    "Infinix Hot 20 (No Sides)",
    "Infinix Hot 30 (4G)",
    "Infinix Hot 30 (5G) (Only Back)",
    "Infinix Hot 30i",
    "Infinix Hot 40",
    "Infinix Hot 40i",
    "Infinix Hot 50 (5G) (Only Back)",
    "Infinix Hot 50i",
    "Infinix Hot 50 Pro",
    "Infinix Hot 50 Pro Plus",
    "Infinix Hot 60 (5G)",
    "Infinix Hot 60i (4G)",
    "Infinix Hot 60i (5G)",
    "Infinix Hot 60 Pro",
    "Infinix Hot 60 Pro Plus",
    "Infinix Note 2",
    "Infinix Note 3",
    "Infinix Note 4",
    "Infinix Note 4 Pro",
    "Infinix Note 5",
    "Infinix Note 5 Stylus",
    "Infinix Note 6",
    "Infinix Note 7",
    "Infinix Note 7 Lite",
    "Infinix Note 8",
    "Infinix Note 8i",
    "Infinix Note 10",
    "Infinix Note 10 Lite",
    "Infinix Note 10 Pro",
    "Infinix Note 11",
    "Infinix Note 11 Pro",
    "Infinix Note 11s",
    "Infinix Note 12",
    "Infinix Note 12 Pro (X676B)",
    "Infinix Note 12 Pro 5G",
    "Infinix Note 12i (No Sides)",
    "Infinix Note 12i 2022 (No Sides)",
    "Infinix Note 30 (5G)",
    "Infinix Note 30 (X6716B)",
    "Infinix Note 30 Pro",
    "Infinix Note 40 (4G)",
    "Infinix Note 40 (5G) (Only Back)",
    "Infinix Note 40X (5G) (Only Back)",
    "Infinix Note 40 Pro (4G)",
    "Infinix Note 40 Pro (5G)",
    "Infinix Note 40 Pro Plus (5G)",
    "Infinix Note 50 (4G)",
    "Infinix Note 50s (5G)",
    "Infinix Note 50x (5G)",
    "Infinix Note 50 Pro (4G)",
    "Infinix Note 50 Pro Plus (5G)",
    "Infinix Note 60 (5G)",
    "Infinix Note 60 Pro (5G)",
    "Infinix GT 10 Pro 5G (No Sides)",
    "Infinix GT 20 Pro (5G)",
    "Infinix GT 30 (5G)",
    "Infinix GT 30 Pro (5G)",
    "Infinix S2 Pro",
    "Infinix S3",
    "Infinix S3x",
    "Infinix S4",
    "Infinix S5",
    "Infinix S5 Pro",
    "Infinix S5 Lite (No Sides)",
    "Infinix Smart",
    "Infinix Smart 2",
    "Infinix Smart 2 HD",
    "Infinix Smart 2 Pro",
    "Infinix Smart 3 (No Sides)",
    "Infinix Smart 3 Plus",
    "Infinix Smart 4",
    "Infinix Smart 4 Plus (No Sides)",
    "Infinix Smart 5",
    "Infinix Smart 6",
    "Infinix Smart 6 Plus",
    "Infinix Smart 7 (Only Back)",
    "Infinix Smart 7 Plus (Only Back)",
    "Infinix Smart 8 (Only Back)",
    "Infinix Smart 8 HD (Only Back)",
    "Infinix Smart HD 2021",
    "Infinix Zero 5",
    "Infinix Zero 5 Pro",
    "Infinix Zero 5G (No Sides)",
    "Infinix Zero 5G 2023 (No Sides)",
    "Infinix Zero 4 (No Sides)",
    "Infinix Zero 8",
    "Infinix Zero 8i",
    "Infinix Zero 20",
    "Infinix Zero 30 5G",
    "Infinix Zero 40 (4G)",
    "Infinix Zero X",
    "Infinix Zero X Pro",
    "Infinix Zero Ultra (No Sides)",
    "Infinix X660",
    "Infinix X680 (No Sides)",
    "Infinix G96"
  ],
  "NUBIA REDMAGIC": [
    "Nubia N1 (Only Back)",
    "Nubia N1 Lite (Only Back)",
    "Nubia N2 (Only Back)",
    "Nubia Red Magic (5G) (Only Back)",
    "Nubia Red Magic 5S (Only Back)",
    "Nubia Red Magic 7 (Only Back)",
    "Nubia Red Magic 9 Pro (5G) (Only Back)",
    "Nubia Z60 Ultra (5G) (Only Back)"
  ],
  "Lenovo": [
    "Lenovo K3 Note",
    "Lenovo K4 Note",
    "Lenovo K5 Note",
    "Lenovo K6 Note",
    "Lenovo K8",
    "Lenovo K8 Note",
    "Lenovo K8 Plus",
    "Lenovo K9 (No Sides)",
    "Lenovo K10 Note (No Sides)",
    "Lenovo K12 Note (No Sides)",
    "Lenovo Vibe P1",
    "Lenovo Vibe P1 Turbo",
    "Lenovo Vibe P2",
    "Lenovo Vibe K6 Power"
  ],
  "LG": [
    "Lg G5",
    "Lg G6",
    "Lg G7",
    "Lg G7 Thinq",
    "Lg G8X Thinq",
    "Lg Q7",
    "Lg V20",
    "Lg W30 (No Sides)",
    "Lg V30 Plus (No Sides)",
    "Lg V30 Thinq Q",
    "Lg V40 Thinq",
    "Lg V50s Thinq 5G",
    "Lg V60 Thinq 5G (No Sides)",
    "Lg Velvet",
    "Lg Wing 5G",
    "Lg W41 Plus (No Sides)",
    "Lg Q Stylus",
    "Lg Q6 Plus (Only Back)",
    "Lg W41 Pro 2022 (No Sides)"
  ],
  "Lava": [
    "Lava Amoled 2 (5G) (Only Back)",
    "Lava Agni (5G) (Only Back)",
    "Lava Agni 2 (5G)",
    "Lava Agni 3 (5G) (Only Back)",
    "Lava Z2",
    "Lava Z3 (Only Back)",
    "Lava Z6 (Only Back)",
    "Lava Z66 (Only Back)",
    "Lava Blaze (4G)",
    "Lava Blaze (5G)",
    "Lava Blaze Curve (5G)",
    "Lava Blaze X (5G) (Only Back)",
    "Lava Blaze Duo (5G) (Only Back)",
    "Lava Blaze 2 (4G) (Only Back)",
    "Lava Blaze 2 (5G) (Only Back)",
    "Lava Blaze 2 Pro (5G) (Only Back)",
    "Lava Blaze 3 (5G) (Only Back)",
    "Lava Blaze Pro (4G)",
    "Lava Blaze Pro (5G) (Only Back)",
    "Lava Play Ultra (5G) (Only Back)",
    "Lava Storm (5G) (Only Back)",
    "Lava Yuva (5G) (Only Back)",
    "Lava Yuva Star"
  ],
  "Micromax": [
    "Micromax IN 1B (E7533)",
    "Micromax IN 2B (No Sides)",
    "Micromax IN Note 1 (E7746)",
    "Micromax IN Note 2 (Only Back)",
    "Micromax Canvas Fire 4G Plus"
  ],
  "Tecno": [
    "Tecno Camon Sky2 IN1 Pro (No Sides)",
    "Tecno Camon F3",
    "Tecno Camon I Ace 2 (No Sides)",
    "Tecno Camon I Ace 2X",
    "Tecno Camon I Air (No Sides)",
    "Tecno Camon I Air 2 Plus",
    "Tecno Camon I Click (No Sides)",
    "Tecno Camon I Sky 2 (No Sides)",
    "Tecno Camon I2 (No Sides)",
    "Tecno Camon I2X",
    "Tecno Camon I4 (No Sides)",
    "Tecno Camon ISKY 3 (No Sides)",
    "Tecno Camon 12 Air",
    "Tecno Camon 15 (No Sides)",
    "Tecno Camon 15 Pro",
    "Tecno Camon 16",
    "Tecno Camon 16 Premier",
    "Tecno Camon 17",
    "Tecno Camon 17P (No Sides)",
    "Tecno Camon 17 Pro (No Sides)",
    "Tecno Camon 18",
    "Tecno Camon 18I (No Sides)",
    "Tecno Camon 18P",
    "Tecno Camon 18T",
    "Tecno Camon 18 Premier (No Sides)",
    "Tecno Camon 19",
    "Tecno Camon 19 Pro (No Sides)",
    "Tecno Camon 19 Neo",
    "Tecno Camon 20 (CK6)",
    "Tecno Camon 20 Premier (5G) (Only Back)",
    "Tecno Camon 20 Pro (4G) (Only Back)",
    "Tecno Camon 20 Pro (5G)",
    "Tecno Spark Plus (No Sides)",
    "Tecno Spark Power (No Sides)",
    "Tecno Spark 2 (No Sides)",
    "Tecno Spark Power 2 (No Sides)",
    "Tecno Spark 4",
    "Tecno Spark 4 Air",
    "Tecno Spark 5",
    "Tecno Spark 5 Pro (Only Back)",
    "Tecno Spark 6",
    "Tecno Spark 6 Air",
    "Tecno Spark 6 Go",
    "Tecno Spark 6 Go 2021",
    "Tecno Spark 7",
    "Tecno Spark 7T",
    "Tecno Spark 7 Go (No Sides)",
    "Tecno Spark 7 Pro",
    "Tecno Spark 8",
    "Tecno Spark 8C",
    "Tecno Spark 8P",
    "Tecno Spark 8 32gb",
    "Tecno Spark 8 Pro",
    "Tecno Spark 8T (No Sides)",
    "Tecno Spark 9 (No Sides)",
    "Tecno Spark 10C",
    "Tecno Spark 10 Pro",
    "Tecno Spark 10 (5G)",
    "Tecno Spark 10 (4G) (KI5q)",
    "Tecno Spark 20 (KJ5)",
    "Tecno Spark 20C",
    "Tecno Spark 20 Pro (4G)",
    "Tecno Spark 20 Pro (5G)",
    "Tecno Spark 20 Pro Plus",
    "Tecno Spark 30",
    "Tecno Spark 30 Pro",
    "Tecno Spark 30C (4G)",
    "Tecno Spark 30C (5G)",
    "Tecno Spark Go 1",
    "Tecno Spark Go 2",
    "Tecno Spark Go 2020 (No Sides)",
    "Tecno Spark Go 2021",
    "Tecno Spark Go 2022",
    "Tecno Spark Go 2023",
    "Tecno Spark Go (5G)",
    "Tecno Spark Go Plus",
    "Tecno Pova",
    "Tecno Pova Curve (5G)",
    "Tecno Pova Curve 2 (5G)",
    "Tecno Pova Slim (5G)",
    "Tecno Pova 2 (No Sides)",
    "Tecno Pova 3",
    "Tecno Pova 4 (No Sides)",
    "Tecno Pova 5 (LH7n)",
    "Tecno Pova 5 Pro (5G)",
    "Tecno Pova 6 Pro (5G)",
    "Tecno Pova 6 Neo (4G) (Only Back)",
    "Tecno Pova 6 Neo (5G) (Only Back)",
    "Tecno Pova 7 (5G)",
    "Tecno Pova 7 Pro (5G) (Only Back)",
    "Tecno Pova Neo (LE6)",
    "Tecno Pova Neo (5G) (No Sides)",
    "Tecno Pova Neo 2",
    "Tecno Pova Neo 3",
    "Tecno I3 (No Sides)",
    "Tecno I3 Pro (No Sides)",
    "Tecno I5 (No Sides)",
    "Tecno IA5 (No Sides)",
    "Tecno I5 Pro (No Sides)",
    "Tecno ID6 (No Sides)",
    "Tecno I7 (No Sides)",
    "Tecno IN1 (No Sides)",
    "Tecno IN2 (No Sides)",
    "Tecno IN3 (No Sides)",
    "Tecno IN5 (No Sides)",
    "Tecno IN6 (No Sides)",
    "Tecno Pop 2F (No Sides)",
    "Tecno Pop 3 (No Sides)",
    "Tecno Pop 4",
    "Tecno Pop 5 (No Sides)",
    "Tecno Pop 5 Go (No Sides)",
    "Tecno Pop 5P (No Sides)",
    "Tecno Pop 5 Pro",
    "Tecno Pop 6 (No Sides)",
    "Tecno Pop 6 Pro (No Sides)",
    "Tecno Pop 6 Go (No Sides)",
    "Tecno Pop 7 Pro (BF7h)",
    "Tecno Pop 8 (4G) (Only Back)",
    "Tecno Pop 9 (4G) (Only Back)",
    "Tecno Pop 9 (5G) (Only Back)",
    "Tecno Power 2 (No Sides)",
    "Tecno Pouvoir 4",
    "Tecno Phantom X (AC8)",
    "Tecno Phantom X2 (5G)",
    "Tecno Phantom X2 Pro (5G) (Only Back)",
    "Tecno Phantom V Fold (5G)"
  ],
  "Meizu": [
    "Meizu 16 (M882H)",
    "Meizu 16S",
    "Meizu 16X (M872H)",
    "Meizu C9 pro (M819H)",
    "Meizu U10",
    "Meizu 16",
    "Meizu M2 Note",
    "Meizu M3 Note",
    "Meizu M3s (Y685H)"
  ],
  "Blackberry": [
    "Blackberry Passport",
    "Blackberry Priv",
    "Blackberry Z10"
  ],
  "Gionee": [
    "Gionee F103 Pro",
    "Gionee P5 Mini",
    "Gionee P5W",
    "Gionee Max 2020"
  ],
  "HTC": [
    "HTC Desire 820",
    "HTC Desire 820 G Plus",
    "HTC Desire 828",
    "HTC One A9",
    "HTC One M7",
    "HTC One M8",
    "HTC One M9",
    "HTC One M9 Plus",
    "HTC U11",
    "HTC U11+"
  ],
  "10. or G": [
    "10. or G (Only Back)",
    "10. or G 2 (Only Back)",
    "10. or E (Only Back)",
    "10. or D (Only Back)"
  ],
  "Sony": [
    "Sony Xperia 1 (Only Back)",
    "Sony Xperia 1 II (5G) (Only Back)",
    "Sony Xperia 1 III (5G) (Only Back)",
    "Sony Xperia 1 V (5G) (Only Back)",
    "Sony R1 Dual (Only Back)"
  ],
  "ITEL": [
    "ITEL A48",
    "ITEL A60",
    "ITEL A70",
    "ITEL A70 (A665L) (Only Back)",
    "ITEL P55 (5G) (Only Back)",
    "ITEL P55T",
    "ITEL P55 Plus (Only Back)",
    "ITEL S23 (S665L)",
    "ITEL S23 Plus (Only Back)"
  ],
  "Jio": [
    "Jio Phone Next"
  ]
};